### PR TITLE
patreon button & link updates

### PR DESCRIPTION
**Pull request by dharness**
I also moved the repo if you didn't notice, so I had to update all the links in the readme

### CODE REVIEW

**Comment by heatherbooker** [comment]
Ah yeah now I see em. Looks good!

**Comment by heatherbooker** [comment]
Hey @dharness, What about changing the "email me" email at the bottom of the readme to be `rcw@kingofthestack.com` or `react-chat-window@...` or something like that?

**Comment by dharness** [comment]
@heatherbooker I'd rather not maintain additional emails - I find I miss emails from hello@kingofthestack.com as is

**Comment by heatherbooker** [comment]
1. Does / will this patreon still exist / be relevant?
2. If yes - merge?
3. If no - remove then merge?

**Pull request merged**
